##########################
# Parameters below control algorithm settings
# Initialisation - no. of clusters
initialZ: 100
# Controls the number of transcripts selected to consider in clustering
filter: 1000
# Burn-in, total number of MCMC chain iterations, thinning out interval and total number of chains
burnin: 500
iter: 1000
thin: 10
chains: 4
# model - nb or mult
model: "nbzi"
